# Generated by Django 2.0.7 on 2018-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('C_time', models.DateTimeField(verbose_name='创建时间')),
                ('c_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.clify', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.CreateModel(
            name='article_nr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
            },
        ),
        migrations.CreateModel(
            name='article_zan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.article', verbose_name='文章')),
                ('user_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.user1', verbose_name='用户')),
                ('azn', models.BooleanField(verbose_name='赞')),
            ],
            options={
                'verbose_name': '文章赞踩',
                'verbose_name_plural': '文章赞踩',
            },
        ),
        migrations.CreateModel(
            name='boke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffixURL', models.CharField(max_length=10, verbose_name='后缀名')),
                ('theme', models.CharField(max_length=20, verbose_name='个人主题')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('present', models.CharField(max_length=50, verbose_name='基本介绍')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
            },
        ),
        migrations.CreateModel(
            name='clify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
                ('boke_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.boke', verbose_name='所属博客')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论')),
                ('article_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.article', verbose_name='文章')),
                ('user_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.user1', verbose_name='用户')),
                ('comment_id', models.OneToOneField(on_delete=None, parent_link=True, to='dataManage.comment', verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='ensure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('T_user', models.ForeignKey(on_delete=None, parent_link=True, related_name='T_user', to='dataManage.user1', verbose_name='提问人')),
                ('D_user', models.ForeignKey(null=True, on_delete=None, parent_link=True, related_name='D_user', to='dataManage.user1', verbose_name='回答人')),
                ('state', models.IntegerField(choices=[(1, '处理中'), (0, '未处理'), (2, '已处理')], default=0, verbose_name='状态')),
                ('C_time', models.DateTimeField(verbose_name='创建时间')),
                ('T_time', models.DateTimeField(null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '报障单',
                'verbose_name_plural': '报障单',
            },
        ),
        migrations.CreateModel(
            name='fufen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_Id', models.ForeignKey(on_delete=None, parent_link=True, related_name='user_star', to='dataManage.user1', verbose_name='明星')),
                ('fans_id', models.ForeignKey(on_delete=None, parent_link=True, related_name='user_fans', to='dataManage.user1', verbose_name='粉丝')),
            ],
            options={
                'verbose_name': '粉丝表',
                'verbose_name_plural': '粉丝表',
            },
        ),
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='标签名')),
                ('boke_id', models.ForeignKey(on_delete=None, parent_link=True, to='dataManage.boke', verbose_name='所属博客')),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('mail', models.CharField(max_length=20, verbose_name='邮箱')),
                ('img', models.ImageField(upload_to='static/user_img/', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.AddField(
            model_name='boke',
            name='user_id',
            field=models.OneToOneField(on_delete=None, to='dataManage.user1', verbose_name='博客主人'),
        ),
        migrations.AlterUniqueTogether(
            name='article_zan',
            unique_together={('article_id', 'user_id')},
        ),
        migrations.AddField(
            model_name='article_nr',
            name='article_xx_id',
            field=models.OneToOneField(on_delete=None, to='dataManage.article', verbose_name='文章信息'),
        ),
        migrations.AddField(
            model_name='article',
            name='label_id',
            field=models.ManyToManyField(to='dataManage.label', verbose_name='文章标签'),
        ),
    ]
