# Generated by Django 2.0.7 on 2018-09-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensure',
            name='state',
            field=models.IntegerField(choices=[(2, '已处理'), (0, '未处理'), (1, '处理中')], default=0, verbose_name='状态'),
        ),
    ]
