# Generated by Django 2.0.7 on 2018-09-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0004_auto_20180923_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user1',
            options={},
        ),
        migrations.AlterField(
            model_name='ensure',
            name='state',
            field=models.IntegerField(choices=[(1, '处理中'), (2, '已处理'), (0, '未处理')], default=0, verbose_name='状态'),
        ),
    ]
