# Generated by Django 2.0.7 on 2018-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0005_auto_20180923_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user1',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AddField(
            model_name='article',
            name='zyfenlei',
            field=models.IntegerField(choices=[(0, 'python'), (1, 'java'), (2, 'php'), (2, 'C++')], default=0, verbose_name='主页分类'),
        ),
        migrations.AlterField(
            model_name='ensure',
            name='state',
            field=models.IntegerField(choices=[(1, '处理中'), (0, '未处理'), (2, '已处理')], default=0, verbose_name='状态'),
        ),
    ]
