# Generated by Django 2.0.7 on 2018-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0006_auto_20180923_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=None, parent_link=True, to='dataManage.user1', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='zyfenlei',
            field=models.IntegerField(choices=[(1, 'java'), (3, 'C++'), (2, 'php'), (0, 'python')], default=0, verbose_name='主页分类'),
        ),
    ]
