# Generated by Django 2.0.7 on 2018-09-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0010_auto_20180925_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='zyfenlei',
            field=models.IntegerField(choices=[(1, 'java'), (0, 'python'), (3, 'C++'), (2, 'php')], default=0, verbose_name='主页分类'),
        ),
        migrations.AlterField(
            model_name='ensure',
            name='state',
            field=models.IntegerField(choices=[(2, '已处理'), (1, '处理中'), (0, '未处理')], default=0, verbose_name='状态'),
        ),
    ]
