# Generated by Django 2.0.7 on 2018-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0011_auto_20180926_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_nr',
            name='article_xx_id',
        ),
        migrations.AddField(
            model_name='article',
            name='article_nr_id',
            field=models.ForeignKey(default=1, on_delete=None, to='dataManage.article_nr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='zyfenlei',
            field=models.IntegerField(choices=[(1, 'java'), (0, 'python'), (2, 'php'), (3, 'C++')], default=0, verbose_name='主页分类'),
        ),
        migrations.AlterField(
            model_name='ensure',
            name='state',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已处理')], default=0, verbose_name='状态'),
        ),
    ]
