# Generated by Django 2.0.7 on 2018-10-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0013_auto_20181011_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='zyfenlei',
            field=models.IntegerField(choices=[(1, 'java'), (3, 'C++'), (2, 'php'), (0, 'python')], default=0, verbose_name='主页分类'),
        ),
    ]
