# Generated by Django 2.0.7 on 2018-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManage', '0017_auto_20181011_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='zyfenlei',
            field=models.IntegerField(choices=[(3, 'C++'), (2, 'php'), (0, 'python'), (1, 'java')], default=0, verbose_name='主页分类'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='img',
            field=models.ImageField(upload_to='./static/user_img', verbose_name='头像'),
        ),
    ]
