# Generated by Django 2.0.7 on 2018-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barn_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='所有信息都暂时放在这')),
                ('creat_Time', models.CharField(max_length=32, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '畜舍信息',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='公司名字')),
                ('hierarchy', models.IntegerField(choices=[(1, '畜牧中心'), (3, '养殖场管'), (4, '畜舍'), (2, '畜牧公司')], verbose_name='层级')),
                ('creat_Time', models.CharField(max_length=32, verbose_name='创建时间')),
                ('address', models.TextField(verbose_name='地址')),
                ('state', models.TextField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '公司表',
            },
        ),
        migrations.CreateModel(
            name='muen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='菜单名称')),
                ('muen_a', models.IntegerField(choices=[(1, '畜牧中心'), (3, '养殖场管'), (4, '畜舍'), (2, '畜牧公司')], verbose_name='要求不低于这个权限')),
                ('muen_hierarchy', models.ForeignKey(blank=True, null=True, on_delete=None, to='Henhouse_Sys_data.muen', verbose_name='它在那个菜单下')),
            ],
            options={
                'verbose_name': '菜单表',
            },
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=32, verbose_name='角色名称')),
                ('part_a', models.CharField(max_length=32, verbose_name='角色权限')),
            ],
            options={
                'verbose_name': '角色表',
            },
        ),
        migrations.CreateModel(
            name='party_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('part', models.ForeignKey(on_delete=None, parent_link=True, to='Henhouse_Sys_data.part', verbose_name='关联角色')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=None, parent_link=True, to='Henhouse_Sys_data.company', verbose_name='关联公司')),
                ('sex', models.CharField(choices=[('2', '女'), ('1', '男')], max_length=2)),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('state', models.TextField(verbose_name='状态')),
                ('creat_Time', models.CharField(max_length=32, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户表',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='Henhouse_Sys_data.company', verbose_name='被其领导'),
        ),
        migrations.AddField(
            model_name='barn_data',
            name='company',
            field=models.ForeignKey(on_delete=None, to='Henhouse_Sys_data.company', verbose_name='畜舍'),
        ),
    ]
