# Generated by Django 2.0.7 on 2018-11-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='part_name',
            new_name='part',
        ),
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(4, '畜舍'), (2, '畜牧公司'), (3, '养殖场管'), (1, '畜牧中心')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(4, '畜舍'), (2, '畜牧公司'), (3, '养殖场管'), (1, '畜牧中心')], verbose_name='要求不低于这个权限'),
        ),
    ]
