# Generated by Django 2.0.7 on 2018-11-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0002_auto_20181101_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(4, '畜舍'), (3, '养殖场管'), (1, '畜牧中心'), (2, '畜牧公司')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(4, '畜舍'), (3, '养殖场管'), (1, '畜牧中心'), (2, '畜牧公司')], verbose_name='要求不低于这个权限'),
        ),
        migrations.AlterField(
            model_name='party_user',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2),
        ),
    ]
