# Generated by Django 2.0.7 on 2018-11-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0003_auto_20181101_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(3, '养殖场管'), (2, '畜牧公司'), (1, '畜牧中心'), (4, '畜舍')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(3, '养殖场管'), (2, '畜牧公司'), (1, '畜牧中心'), (4, '畜舍')], verbose_name='要求不低于这个权限'),
        ),
        migrations.AlterField(
            model_name='party_user',
            name='state',
            field=models.TextField(blank=True, null=True, verbose_name='状态'),
        ),
    ]
