# Generated by Django 2.0.7 on 2018-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0005_auto_20181101_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_user',
            name='pwd',
            field=models.CharField(default=123456, max_length=32, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(4, '畜舍'), (2, '畜牧公司'), (3, '养殖场'), (1, '畜牧中心')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(4, '畜舍'), (2, '畜牧公司'), (3, '养殖场'), (1, '畜牧中心')], verbose_name='要求不低于这个权限'),
        ),
        migrations.AlterField(
            model_name='party_user',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2),
        ),
    ]
