# Generated by Django 2.0.7 on 2018-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0006_auto_20181101_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='muen',
            name='muen_class_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='muen',
            name='muen_url',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(4, '畜舍'), (1, '畜牧中心'), (2, '畜牧公司'), (3, '养殖场')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(4, '畜舍'), (1, '畜牧中心'), (2, '畜牧公司'), (3, '养殖场')], verbose_name='要求不低于这个权限'),
        ),
    ]
