# Generated by Django 2.0.7 on 2018-11-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0007_auto_20181103_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(3, '养殖场'), (2, '畜牧公司'), (1, '畜牧中心'), (4, '畜舍')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(3, '养殖场'), (2, '畜牧公司'), (1, '畜牧中心'), (4, '畜舍')], verbose_name='要求不低于这个权限'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_class_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='前端class的值'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_url',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单url'),
        ),
        migrations.AlterField(
            model_name='party_user',
            name='sex',
            field=models.CharField(choices=[('2', '女'), ('1', '男')], max_length=2),
        ),
    ]
