# Generated by Django 2.0.7 on 2018-11-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Henhouse_Sys_data', '0010_auto_20181104_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='hierarchy',
            field=models.IntegerField(choices=[(1, '畜牧中心'), (2, '畜牧公司'), (4, '畜舍'), (3, '养殖场')], verbose_name='层级'),
        ),
        migrations.AlterField(
            model_name='muen',
            name='muen_a',
            field=models.IntegerField(choices=[(1, '畜牧中心'), (2, '畜牧公司'), (4, '畜舍'), (3, '养殖场')], verbose_name='要求不低于这个权限'),
        ),
        migrations.AlterField(
            model_name='notice_info',
            name='state',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=None, to='Henhouse_Sys_data.party_user', verbose_name='状态'),
        ),
    ]
